INSERT INTO movies (id, name, main_leads, description) VALUES
(1, 'Mắt Biếc', 'Trần Nghĩa, Trúc Anh', 'Chuyển thể từ tiểu thuyết của Nguyễn Nhật Ánh, kể về mối tình đơn phương của Ngạn dành cho Hà Lan ở làng quê miền Trung.'),
(2, 'Bố Già', 'Trấn Thành, Tuấn Trần', 'Câu chuyện ấm áp và nhiều xung đột giữa người cha già khó tính và cậu con trai trong một xóm nhỏ Sài Gòn.'),
(3, 'Hai Phượng', 'Ngô Thanh Vân, Mai Cát Vi', 'Một người mẹ đơn thân truy đuổi băng nhóm tội phạm để cứu con gái bị bắt cóc.'),
(4, 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh', 'Thịnh Vinh, Trọng Khang, Lâm Thanh Mỹ', 'Bộ phim tuổi thơ trong sáng ở làng quê, xoay quanh tình anh em và những rung động đầu đời.'),
(5, 'Em Chưa 18', 'Kaity Nguyễn, Kiều Minh Tuấn', 'Một nữ sinh tinh nghịch lập kế hoạch ''thuần hóa'' tay chơi có tiếng và gây nên chuyện dở khóc dở cười.'),
(6, 'Cô Ba Sài Gòn', 'Ninh Dương Lan Ngọc, Diễm My', 'Câu chuyện thời trang áo dài và di sản gia đình qua nhiều thế hệ ở Sài Gòn.'),
(7, 'Song Lang', 'Liên Bỉnh Phát, Isaac', 'Tình bạn đặc biệt giữa một tay đòi nợ và kép chính cải lương trong bối cảnh Sài Gòn thập niên 1980.'),
(8, 'Vợ Ba', 'Nguyễn Phương Trà My, Maya', 'Một cô gái trẻ làm vợ ba trong gia đình địa chủ đối mặt với những quy tắc khắc nghiệt và khao khát tự do.'),
(9, 'Tiệc Trăng Máu', 'Thái Hòa, Thu Trang', 'Nhóm bạn thân chơi trò mở điện thoại công khai trong bữa tối, phơi bày những bí mật sốc.'),
(10, 'Ròm', NULL, 'Cậu bé bán số đề mưu sinh giữa Sài Gòn khắc nghiệt, luôn tin vào cơ hội đổi đời.'),
(11, 'Nhà Bà Nữ', 'Trấn Thành, Uyển Ân', 'Mâu thuẫn mẹ con trong một gia đình bán bánh canh cua, nơi ai cũng mang những vết thương riêng.'),
(12, 'Mai', 'Phương Anh Đào, Tuấn Trần', 'Một người phụ nữ nhiều tổn thương dần học cách chữa lành và mở lòng với cuộc sống.'),
(13, 'Cua Lại Vợ Bầu', 'Trấn Thành, Ninh Dương Lan Ngọc', 'Cặp đôi đứng trước lựa chọn hôn nhân khi quá khứ và những rạn nứt bị khơi lại.'),
(14, 'Em Là Bà Nội Của Anh', 'Miu Lê, Ngô Kiến Huy', 'Một bà cụ bỗng trở lại tuổi đôi mươi, theo đuổi ước mơ ca hát còn dang dở.'),
(15, 'Để Mai Tính', 'Dustin Nguyễn, Kathy Uyên', 'Chàng trai làm nghề bưng bê ở khách sạn vô tình vướng vào chuyện tình rắc rối với một nữ diễn viên.'),
(16, 'Để Mai Tính 2', 'Thái Hòa, Diễm My 9x', 'Nhân vật Hội trở lại với những tình huống dở khóc dở cười khi tìm kiếm người yêu đích thực.'),
(17, 'Quả Tim Máu', 'Thái Hòa, Nhã Phương', 'Sau ca ghép tim, một người phụ nữ liên tục gặp những hiện tượng đáng sợ liên quan đến chủ nhân trái tim cũ.'),
(18, 'Scandal: Bí Mật Thảm Đỏ', 'Vân Trang, Maya', 'Bức màn hậu trường showbiz với toan tính, ghen ghét và những bí mật chết người.'),
(19, 'Giao Lộ Định Mệnh', 'Hồng Ánh, Bình Minh', 'Một vụ tai nạn kéo theo chuỗi sự kiện bí ẩn, đan xen số phận nhiều con người.'),
(20, 'Tèo Em', 'Thái Hòa, Johnny Trí Nguyễn', 'Hai anh em trái tính cùng lên đường trong chuyến đi đầy trắc trở và hài hước.'),
(21, 'Long Ruồi', 'Thái Hòa, Tina Tình', 'Kẻ giang hồ giống y như trùm xã hội đen bị hoán đổi vị trí, gây ra nhiều rắc rối.'),
(22, 'Bẫy Rồng (Clash)', 'Ngô Thanh Vân, Johnny Trí Nguyễn', 'Nhóm tội phạm thực hiện phi vụ cướp táo bạo, đối mặt với phản bội và tình cảm dang dở.'),
(23, 'Dòng Máu Anh Hùng', 'Johnny Trí Nguyễn, Ngô Thanh Vân', 'Chuyện tình giữa chiến sĩ nghĩa quân và con quan trong bối cảnh Việt Nam thời thuộc địa.'),
(24, 'Áo Lụa Hà Đông', NULL, 'Bi kịch của một gia đình nghèo giữa thời chiến, gắn với chiếc áo dài trắng.'),
(25, 'Hotboy Nổi Loạn', 'Lương Mạnh Hải, Hồ Vĩnh Khoa', 'Câu chuyện về tình yêu, bản dạng và sự sống còn nơi đô thị.'),
(26, 'Cánh Đồng Bất Tận', 'Đỗ Thị Hải Yến, Dustin Nguyễn', 'Hai chị em lênh đênh cùng người cha trên những cánh đồng ngập nước miền Tây.'),
(27, 'Trúng Số', 'Dustin Nguyễn, Thu Trang', 'Tấm vé số bất ngờ mang lại những tình huống dở khóc dở cười cho cả xóm.'),
(28, 'Chàng Trai Năm Ấy', 'Sơn Tùng M-TP, Hari Won', 'Câu chuyện cảm động lấy cảm hứng từ ca sĩ Wanbi Tuấn Anh và những người bạn.'),
(29, 'Nụ Hôn Thần Chết', 'Johnny Trí Nguyễn, Thanh Hằng', 'Thần Chết lạc vào trần gian và nảy sinh tình cảm với một cô gái.'),
(30, 'Cô Dâu Đại Chiến', 'Huy Khánh, Vân Trang', 'Những cô dâu tương lai liên minh để vạch mặt gã sở khanh lắm chiêu.'),
(31, 'Yêu Đi, Đừng Sợ!', 'Nhã Phương, Ngô Kiến Huy', 'Ảo thuật gia nhút nhát gặp cô gái bí ẩn, tình yêu giúp anh vượt qua nỗi sợ.'),
(32, 'Bao Giờ Có Yêu Nhau', 'Minh Hằng, Quý Bình', 'Chuyện tình đẫm chất liêu trai, xoay quanh vòng luân hồi và định mệnh.'),
(33, 'Sài Gòn, Anh Yêu Em', NULL, 'Nhiều câu chuyện nhỏ đan xen về tình yêu và gia đình giữa lòng Sài Gòn.'),
(34, 'Vệ Sĩ Sài Gòn', 'Kim Lý, Thái Hòa', 'Hai vệ sĩ tính cách trái ngược phải hợp tác bảo vệ một thân chủ đặc biệt.'),
(35, 'Hồn Papa, Da Con Gái', 'Thái Hòa, Kaity Nguyễn', 'Một buổi sáng tỉnh dậy, hai cha con hoán đổi thân xác và học cách thấu hiểu nhau.'),
(36, 'Trạng Quỳnh', 'Quốc Anh, Nhã Phương', 'Chàng nho sinh láu lỉnh cùng bạn bè phá giải nhiều âm mưu chốn quan trường.'),
(37, 'Tháng Năm Rực Rỡ', 'Hoàng Yến Chibi, Jun Vũ', 'Nhóm bạn nữ thời trung học hội ngộ, hàn gắn quá khứ và tình bạn.'),
(38, 'Gái Già Lắm Chiêu 3', 'Ninh Dương Lan Ngọc, NSND Lê Khanh', 'Màn đấu trí – đấu sang giữa nàng Mễ Lan và gia tộc Lý Lệ Hà.'),
(39, 'Chị Chị Em Em', 'Thanh Hằng, Chi Pu', 'Đằng sau mối quan hệ chị em thân thiết là toan tính và ghen tuông.'),
(40, 'Chị Chị Em Em 2', 'Ninh Dương Lan Ngọc, Kaity Nguyễn', 'Cuộc đối đầu trong giới giải trí với nhiều cú twist liên tiếp.'),
(41, 'Siêu Lừa Gặp Siêu Lầy', 'Anh Tú, Mạc Văn Khoa', 'Hai kẻ lừa đảo tay mơ bắt tay thực hiện những phi vụ dở khóc dở cười.'),
(42, 'Bẫy Ngọt Ngào', 'Minh Hằng, Bảo Anh', 'Những bí mật hôn nhân bị lật mở khi nhóm bạn tái ngộ.'),
(43, 'Chuyện Ma Gần Nhà', NULL, 'Tuyển tập các truyền thuyết đô thị rùng rợn được kể lại theo góc nhìn hiện đại.'),
(44, '578: Phát Đạn Của Kẻ Điên', NULL, 'Người cha truy tìm kẻ bắt cóc, lao vào hành trình báo thù nghẹt thở.'),
(45, 'Đêm Tối Rực Rỡ!', 'Phương Anh Đào, Huỳnh Kiến An', 'Đêm tang lễ hé lộ sự thật đau lòng của một gia đình.'),
(46, 'Tro Tàn Rực Rỡ', NULL, 'Bi kịch tình yêu và ghen tuông của những người phụ nữ vùng sông nước.'),
(47, 'Thưa Mẹ Con Đi', 'Lãnh Thanh, Võ Điền Gia Huy', 'Chàng Việt kiều đưa người yêu về ra mắt, đối diện định kiến và tình thân.'),
(48, 'Người Bất Tử', 'Quách Ngọc Ngoan, Jun Vũ', 'Người đàn ông bị nguyền rủa sống mãi, mang theo mối hận tình qua nhiều thời kỳ.'),
(49, 'Tấm Cám: Chuyện Chưa Kể', 'Hạ Vi, Ninh Dương Lan Ngọc', 'Cổ tích Việt Nam được kể lại với bối cảnh và tạo hình hiện đại.'),
(50, 'Cô Gái Đến Từ Hôm Qua', 'Ngô Kiến Huy, Miu Lê', 'Chuyện tình tuổi học trò trong veo, về những rung động đầu đời và ký ức đẹp.');